### ISSUE TITLE
where is @oclif/test documented?

### ISSUE THREAD

**Issue by swyxio** [oclif/test#40]
the README seems pretty light and the https://oclif.io/docs/testing docs just refer me to you. would love some pointers!

**Comment by rori4** [comment]
I guess they leave it to https://github.com/oclif/fancy-test for the documentation of the `@oclif/test`

**Comment by bilalq** [comment]
One thing that I ended up wasting a lot of time on was figuring out how to write a simple test for the '--help flag'. That's all the functionality my command had as a starting point, so I figured that'd be a trivial example to start with. Turns out that the help flag throws an Error to exit early from the command, so the test needs to catch that first. I thought something was wrong with my test setup to make it fail the way it was.

Here's how to make it work:

```typescript
import { expect, test } from '@oclif/test'

describe('example', () => {
  test
    .stdout()
    .command(['example', '--help'])
    .catch('EEXIT: 0')
    .it('runs login --help', (ctx) => {
      expect(ctx.stdout).to.contain('Whatever text you want to check for')
    })
})
```

**Comment by tvillaren** [comment]
Just adding a comment for future readers, as I add to adapt the workaround above to use a RegEx instead of the `'EEXIT: 0'` string: 

```ts
describe('example', () => {
  test
    .stdout()
    .command(['example', '--help'])
    .catch(/EEXIT: 0/)
    .it('runs login --help', (ctx) => {
      expect(ctx.stdout).to.contain('Whatever text you want to check for')
    })
})
```
