### ISSUE TITLE
Error: Expected to exit with code 1 but it ran without exiting

### ISSUE THREAD

**Issue by JarnoRFB** [oclif/test#465]
I am currently trying to test that a command exits with code 1. In the command, the code simply calls `this.exit(1)` and the test I am trying to assert with `.exit(1)`. However, I am getting the error `Error: Expected to exit with code 1 but it ran without exiting`. See [PR](https://github.com/asyncapi/cli/pull/1068) for context.

I have the suspicion that the `exit` test would always fail, as its [run](https://github.com/oclif/test/blob/main/src/exit.ts#L20) method always throws an error.  How can I handle this situation?

Thanks in advance!

**Comment by mdonnalley** [comment]
@JarnoRFB Calling `this.exit` throws an error, which the `exit` hook's `catch` method is supposed to pick up. If the `run` method is executed instead of the `catch` - that means that you're command didn't throw an error, which is why it's telling you that it ran without exiting.

If you modify the the `catch` method on the base command class is to throw an error [here](https://github.com/asyncapi/cli/blob/master/src/base.ts#L10) then your test will begin passing.

**Comment by JarnoRFB** [comment]
@mdonnalley That makes a lot of sense. Thank you for the clarification! 
As it is implemented right now, the base class seems to catch any error and just set the exit code to 1 in this case. Is there any way to assert the exit code in the test without requiring the command to throw an error?

**Comment by mdonnalley** [comment]
You can just check that `process.exitCode` has been set to the expected code

**Comment by JarnoRFB** [comment]
Thanks, that seems to work just fine 👍
