### ISSUE TITLE
Source maps do not work with multi-commands and mocha

### ISSUE THREAD

**Issue by zbarbuto** [oclif/test#50]
I've had issues trying to get breakpoints to work properly in VSCode when running mocha tests.

After a bunch of digging I've managed to track it down to the `.command()` helper in oclif/test.

You can reproduce the issue by using the following launch.json

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": ["<node_internals>/**"],
      "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
      "args": ["--forbid-only", "${relativeFile}"]
    }
  ]
}
```

To debug a test file in a single and multi command oclif project.

You'll notice that if you put a breakpoint in the `run()` method of a single-command project, the breakpoint will hit as expected (note that a single-command project does not use the `command()` helper and just requires the class in to execute)
If you put the breakpoint in an empty multi-command project it does not hit correctly (shortly after you start debugging, the breakpoint moves).

I've managed to create my own hack-workaround version of `command` which allows debugging tests with proper breakpoints but I think there is some behind-the scenes double-registering of `ts-node` happening which is causing `.command()` to cause source maps to get out of whack.

Here is my workaround

```ts
export const customTest = test.register('run', runCommand);
function runCommand(args: string[]) {
  const [command, ...argv] = args;
  const relativePath = command.split(':');
  const fullPath = join(__dirname, '../src/commands/', ...relativePath);
  const ctor = require(fullPath).default;
  return {
    run() {
     return ctor.run(argv);
    }
  };
}

// Usage:
customTest
  .stdout()
  // .run() instead of .command()
  .run(['mycommand:foo', 'arg1', 'arg2'])
  .it(' ... ', () => {});
```

**Comment by riggtravis** [comment]
This might explain the issues I've been having trying to use istanbul test coverage reporting with mocha

**Comment by OldSneerJaw** [comment]
After a fair bit of yak-shaving, I found a less invasive workaround to this problem. It seems the issue may be something to do with how `@oclif/config`'s [`load` function](https://github.com/oclif/config/blob/v1.17.0/src/config.ts#L567) imports/loads a project's command modules. I haven't dug in deeper to figure out why exactly, but I found that, if one uses Node.js's `require` (_not_ ES6 `import`) to import each command module _before_ they are imported/loaded by invoking `@oclif/test`'s `.command` helper, nyc/istanbul will report the correct line numbers.

The simplest way I found to accomplish this was to create a `test-utils.ts` module in the `test/` directory with the following contents and then to import the `expect` and `test` functions directly from it instead of from `@oclif/test` to ensure the workaround is executed before any command test cases have the chance to invoke the `.command` helper. Note that you'll need to ensure `package.json`'s `devDependencies` section includes a reference to the [`glob`](https://www.npmjs.com/package/glob) library to use this code verbatim. Also, you may notice that it filters out test modules (files that end in `.test.ts`), which may not be necessary depending on how your project's files are laid out (i.e. if the project's test files are stored next to the corresponding source files, it is applicable, but probably not otherwise), but I've included it here for the sake of robustness.

NOTE: I've only tested this with `@oclif/command` 1.8.0, `@oclif/config` 1.17.0, `@oclif/test` 1.2.8, `mocha` 9.1.0 and `nyc` 15.1.0. YMMV if you're on different versions.

```typescript
import * as fs from 'fs'
import {join} from 'path'
import {glob} from 'glob'

export {expect, test} from '@oclif/test'

function preloadCommands() {
  // Adjust the path below if you put this module somewhere other than a top-level "test" directory
  const commandsDir = fs.opendirSync(join(__dirname, '..', 'src', 'commands'))

  const allTsFileNames = glob.sync('**/*.ts', {cwd: commandsDir.path})
  const testFileNames = glob.sync('**/*.test.ts', {cwd: commandsDir.path})

  allTsFileNames.forEach(filename => {
    if (!testFileNames.includes(filename)) {
      const commandPath = join(commandsDir.path, filename)
      require(commandPath)
    }
  })
}

preloadCommands()
```

**Comment by DumpySquare** [comment]
The above got me working.  Thanks a ton.  Hopefully this gets fixed at some point.
